# This file is a template, and might need editing before it works on your project.
image: docker:git

services:
  - docker:dind

build:
#  stage: build
# Cannot build the image on GitLab since it depends on parabank.war. I don't want to put that
# in GitLab (though I am happy to put the docker image built from it on Gitlab! :) )
#  script:
#    - docker build -t registry.gitlab.com/integrationqa/iqa/demos/docker/parabank:latest parabank
#
# test:
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker run -itd --name test_base_parabank registry.gitlab.com/integrationqa/iqa/demos/docker/parabank:latest
    - docker stop test_base_parabank

# deploy:
#   stage: deploy
#   script: docker push registry.gitlab.com/integrationqa/iqa/demos/docker/parabank:latest